[package]
name = "fuz"
version = "0.1.0"
authors = ["Zhu Zihao <all_but_last@163.com>"]
edition = "2018"
publish = false

[lib]
path = "src/lib.rs"
name = "fuz_core"
crate-type = ["cdylib"]

[dependencies]
emacs = "0.18"
fuzzy-matcher = "0.3"

[profile.release]
opt-level = 3
lto = "thin"